spring.application.name=mini-notion
# 1. Th\u00f4ng tin k\u1ebft n\u1ed1i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mini_notion_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=anhmy1312
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. C\u1ea5u h\u00ecnh Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
